### ISSUE TITLE
bug related to OrbitControls.js

### ISSUE THREAD

**Issue by scliubit** [maitreyakv/satellite-constellation-demo#1]
recently this demo is not working here, and i checked the F12 console. The console reports

Uncaught TypeError: quat.clone(...).invert is not a function
    at OrbitControls.js:135
    at new THREE.OrbitControls (OrbitControls.js:268)
    at main.js:16

i looked into obrbitcontrols.js, but didnt figure out where the bug come from...

**Comment by LuanBaviloni** [comment]
Update your index.html:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.js"></script>`

should be:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.js"></script>`

**Comment by scliubit** [comment]
> Update your index.html:
> 
> `<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.js"></script>`
> 
> should be:
> 
> `<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.js"></script>`

thank you, i have also solve the problem by using an older version of three.js

**Comment by parrykhai** [comment]
Yes, to solve that error open OrbitControls.js and change
var quatInverse = quat.clone().invert();       to       var quatInverse = quat.clone().inverse();

**Comment by mrmyn** [comment]
> 是的，要解决该错误，请打开 OrbitControls.js 并更改 var quatInverse = quat.clone().invert(); 到 var quatInverse = quat.clone().inverse();

感谢，很好的解决了我的问题！

**Comment by TheMayFair** [comment]
> Yes, to solve that error open OrbitControls.js and change var quatInverse = quat.clone().invert(); to var quatInverse = quat.clone().inverse();

Thank you, this is exactly what I needed!
